# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# XDC: new/time.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_149M_1/system_rst_ps8_0_149M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_149M_1 || ORIG_REF_NAME==system_rst_ps8_0_149M_1} -quiet] -quiet

# IP: bd/system/ip/system_ps8_0_axi_periph_0/system_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps8_0_axi_periph_0 || ORIG_REF_NAME==system_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_149M_1_1/system_rst_ps8_0_149M_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_149M_1_1 || ORIG_REF_NAME==system_rst_ps8_0_149M_1_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: ip/combine2data_fifo/combine2data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==combine2data_fifo || ORIG_REF_NAME==combine2data_fifo} -quiet] -quiet

# IP: ip/floating_point_compare/floating_point_compare.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_compare || ORIG_REF_NAME==floating_point_compare} -quiet] -quiet

# IP: ip/float_multiply/float_multiply.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_multiply || ORIG_REF_NAME==float_multiply} -quiet] -quiet

# IP: ip/float_add_IP_use_DSP_multilatency/float_add_IP_use_DSP_multilatency.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_add_IP_use_DSP_multilatency || ORIG_REF_NAME==float_add_IP_use_DSP_multilatency} -quiet] -quiet

# IP: ip/fifo_shift_window/fifo_shift_window.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_shift_window || ORIG_REF_NAME==fifo_shift_window} -quiet] -quiet

# IP: ip/stayInstep_fifo/stayInstep_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stayInstep_fifo || ORIG_REF_NAME==stayInstep_fifo} -quiet] -quiet

# IP: ip/post_image_ram/post_image_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==post_image_ram || ORIG_REF_NAME==post_image_ram} -quiet] -quiet

# IP: ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_prerd_toaxi_fifo || ORIG_REF_NAME==image_prerd_toaxi_fifo} -quiet] -quiet

# IP: ip/image_ram/image_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_ram || ORIG_REF_NAME==image_ram} -quiet] -quiet

# IP: ip/image_ram_rd_addr_add/image_ram_rd_addr_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_ram_rd_addr_add || ORIG_REF_NAME==image_ram_rd_addr_add} -quiet] -quiet

# IP: ip/kernel_fifo/kernel_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==kernel_fifo || ORIG_REF_NAME==kernel_fifo} -quiet] -quiet

# IP: ip/head_fifo/head_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==head_fifo || ORIG_REF_NAME==head_fifo} -quiet] -quiet

# IP: ip/sub_unit/sub_unit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_unit || ORIG_REF_NAME==sub_unit} -quiet] -quiet

# IP: ip/head_for_interate_dram/head_for_interate_dram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==head_for_interate_dram || ORIG_REF_NAME==head_for_interate_dram} -quiet] -quiet

# IP: ip/PLL/PLL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] -quiet

# XDC: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps8_0_149M_1/system_rst_ps8_0_149M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_149M_1 || ORIG_REF_NAME==system_rst_ps8_0_149M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps8_0_149M_1/system_rst_ps8_0_149M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_149M_1 || ORIG_REF_NAME==system_rst_ps8_0_149M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps8_0_149M_1/system_rst_ps8_0_149M_1_ooc.xdc

# XDC: bd/system/ip/system_rst_ps8_0_149M_1_1/system_rst_ps8_0_149M_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_149M_1_1 || ORIG_REF_NAME==system_rst_ps8_0_149M_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps8_0_149M_1_1/system_rst_ps8_0_149M_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_149M_1_1 || ORIG_REF_NAME==system_rst_ps8_0_149M_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_rst_ps8_0_149M_1_1/system_rst_ps8_0_149M_1_1_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc

# XDC: ip/combine2data_fifo/combine2data_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==combine2data_fifo || ORIG_REF_NAME==combine2data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_shift_window/fifo_shift_window.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_shift_window || ORIG_REF_NAME==fifo_shift_window} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_shift_window/fifo_shift_window_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_shift_window || ORIG_REF_NAME==fifo_shift_window} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/stayInstep_fifo/stayInstep_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==stayInstep_fifo || ORIG_REF_NAME==stayInstep_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/stayInstep_fifo/stayInstep_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==stayInstep_fifo || ORIG_REF_NAME==stayInstep_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/post_image_ram/post_image_ram_ooc.xdc

# XDC: ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==image_prerd_toaxi_fifo || ORIG_REF_NAME==image_prerd_toaxi_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/image_prerd_toaxi_fifo/image_prerd_toaxi_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==image_prerd_toaxi_fifo || ORIG_REF_NAME==image_prerd_toaxi_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/image_ram/image_ram_ooc.xdc

# XDC: ip/kernel_fifo/kernel_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kernel_fifo || ORIG_REF_NAME==kernel_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/kernel_fifo/kernel_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==kernel_fifo || ORIG_REF_NAME==kernel_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/head_fifo/head_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==head_fifo || ORIG_REF_NAME==head_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/head_fifo/head_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==head_fifo || ORIG_REF_NAME==head_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/head_for_interate_dram/head_for_interate_dram_ooc.xdc

# XDC: ip/PLL/PLL_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/PLL/PLL.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/PLL/PLL_ooc.xdc
